[package]
name = "game_ai_downloader"
version = "0.1.0"
authors = ["block block.cube.lib@gmail.com"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["full"] }
reqwest = "0.10"
regex = "1.3"
anyhow = "1"
futures = "0.3"
